SyatemUI: Fix pocket lock after 13 QPR1
build error -->

 frameworks/base/packages/SystemUI/src/com/android/keyguard/KeyguardUpdateMonitor.java:2103: error: method updateBiometricListeningState in class KeyguardUpdateMonitor cannot be applied to given types;
                        updateBiometricListeningState(BIOMETRIC_ACTION_UPDATE);
                        ^
  required: int,FaceAuthUiEvent
  found: int
  reason: actual and formal argument lists differ in length

[ref] https://github.com/PixysOS-Beta/frameworks_base/commit/917e4bc2144f30c3267bebd53e7a4b4738c34160

Signed-off-by: aswin7469 <aswinas@pixysos.com>